package Views;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

public class frmDashboard extends javax.swing.JFrame {

    /**
     * Creates new form frmDashboard
     */
    public frmDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Paneldefacturacion = new javax.swing.JMenu();
        PanelRegistros = new javax.swing.JMenuItem();
        paneldefacturacion1 = new javax.swing.JMenuItem();
        registrodevehiculos = new javax.swing.JMenuItem();
        registrodeclientes = new javax.swing.JMenuItem();
        registrodereservaciones = new javax.swing.JMenuItem();
        registrodeempleados = new javax.swing.JMenuItem();
        viewdereservas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Kalam", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¡Bienvenido!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(360, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(434, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        escritorio.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Paneldefacturacion.setText("Menu");

        PanelRegistros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        PanelRegistros.setText("Panel de Registros");
        PanelRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelRegistrosActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(PanelRegistros);

        paneldefacturacion1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        paneldefacturacion1.setText("Panel de Facturacion");
        paneldefacturacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paneldefacturacion1ActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(paneldefacturacion1);

        registrodevehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        registrodevehiculos.setText("Registro de Vehiculos");
        registrodevehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodevehiculosActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(registrodevehiculos);

        registrodeclientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        registrodeclientes.setText("Registro de Clientes");
        registrodeclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodeclientesActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(registrodeclientes);

        registrodereservaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        registrodereservaciones.setText("Registro de Reservaciones");
        registrodereservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodereservacionesActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(registrodereservaciones);

        registrodeempleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        registrodeempleados.setText("Registro de Empleados");
        registrodeempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodeempleadosActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(registrodeempleados);

        viewdereservas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        viewdereservas.setText("View Reservas");
        viewdereservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdereservasActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(viewdereservas);

        jMenuBar1.add(Paneldefacturacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void PanelRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelRegistrosActionPerformed

    }//GEN-LAST:event_PanelRegistrosActionPerformed

    private void paneldefacturacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paneldefacturacion1ActionPerformed
    }//GEN-LAST:event_paneldefacturacion1ActionPerformed


    private void viewdereservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdereservasActionPerformed

    }//GEN-LAST:event_viewdereservasActionPerformed


    private void registrodevehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodevehiculosActionPerformed

    }//GEN-LAST:event_registrodevehiculosActionPerformed

    private void registrodeclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodeclientesActionPerformed

    }//GEN-LAST:event_registrodeclientesActionPerformed

    private void registrodereservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodereservacionesActionPerformed

    }//GEN-LAST:event_registrodereservacionesActionPerformed

    private void registrodeempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodeempleadosActionPerformed

    }//GEN-LAST:event_registrodeempleadosActionPerformed

    
    /**
     * @param args the command line arguments
     */

    public JMenuItem getPanelRegistros() {
        return PanelRegistros;
    }

    public void setPanelRegistros(JMenuItem PanelRegistros) {
        this.PanelRegistros = PanelRegistros;
    }

    public JMenu getPaneldefacturacion() {
        return Paneldefacturacion;
    }

    public void setPaneldefacturacion(JMenu Paneldefacturacion) {
        this.Paneldefacturacion = Paneldefacturacion;
    }

    public JMenuItem getPaneldefacturacion1() {
        return paneldefacturacion1;
    }

    public void setPaneldefacturacion1(JMenuItem paneldefacturacion1) {
        this.paneldefacturacion1 = paneldefacturacion1;
    }

    public JMenuItem getRegistrodeclientes() {
        return registrodeclientes;
    }

    public void setRegistrodeclientes(JMenuItem registrodeclientes) {
        this.registrodeclientes = registrodeclientes;
    }

    public JMenuItem getRegistrodereservaciones() {
        return registrodereservaciones;
    }

    public void setRegistrodereservaciones(JMenuItem registrodereservaciones) {
        this.registrodereservaciones = registrodereservaciones;
    }

    public JMenuItem getRegistrodevehiculos() {
        return registrodevehiculos;
    }

    public void setRegistrodevehiculos(JMenuItem registrodevehiculos) {
        this.registrodevehiculos = registrodevehiculos;
    }

    public JMenuItem getViewdereservas() {
        return viewdereservas;
    }

    public void setViewdereservas(JMenuItem viewdereservas) {
        this.viewdereservas = viewdereservas;
    }

    public JMenuItem getRegistrodeempleados() {
        return registrodeempleados;
    }

    public void setRegistrodeempleados(JMenuItem registrodeempleados) {
        this.registrodeempleados = registrodeempleados;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem PanelRegistros;
    private javax.swing.JMenu Paneldefacturacion;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem paneldefacturacion1;
    private javax.swing.JMenuItem registrodeclientes;
    private javax.swing.JMenuItem registrodeempleados;
    private javax.swing.JMenuItem registrodereservaciones;
    private javax.swing.JMenuItem registrodevehiculos;
    private javax.swing.JMenuItem viewdereservas;
    // End of variables declaration//GEN-END:variables
}
