    package Views;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

public class frmDashboard extends javax.swing.JFrame {

    /**
     * Creates new form frmDashboard
     */
    public frmDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Paneldefacturacion = new javax.swing.JMenu();
        PanelRegistros = new javax.swing.JMenuItem();
        paneldefacturacion1 = new javax.swing.JMenuItem();
        registrodevehiculos = new javax.swing.JMenuItem();
        registrodeclientes = new javax.swing.JMenuItem();
        registrodereservaciones = new javax.swing.JMenuItem();
        registrodeempleados = new javax.swing.JMenuItem();
        viewdereservas = new javax.swing.JMenuItem();
        AcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/imagenes/LOGO (5).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        escritorio.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Paneldefacturacion.setText("Menu");

        PanelRegistros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        PanelRegistros.setText("Panel de Registros");
        PanelRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelRegistrosActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(PanelRegistros);

        paneldefacturacion1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        paneldefacturacion1.setText("Panel de Facturacion");
        paneldefacturacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paneldefacturacion1ActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(paneldefacturacion1);

        registrodevehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        registrodevehiculos.setText("Registro de Vehiculos");
        registrodevehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodevehiculosActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(registrodevehiculos);

        registrodeclientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        registrodeclientes.setText("Registro de Clientes");
        registrodeclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodeclientesActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(registrodeclientes);

        registrodereservaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        registrodereservaciones.setText("Registro de Reservaciones");
        registrodereservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodereservacionesActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(registrodereservaciones);

        registrodeempleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        registrodeempleados.setText("Registro de Empleados");
        registrodeempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrodeempleadosActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(registrodeempleados);

        viewdereservas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        viewdereservas.setText("View Reservas");
        viewdereservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdereservasActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(viewdereservas);

        AcercaDe.setText("Acerca de");
        AcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaDeActionPerformed(evt);
            }
        });
        Paneldefacturacion.add(AcercaDe);

        jMenuBar1.add(Paneldefacturacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void PanelRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelRegistrosActionPerformed

    }//GEN-LAST:event_PanelRegistrosActionPerformed

    private void paneldefacturacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paneldefacturacion1ActionPerformed
    }//GEN-LAST:event_paneldefacturacion1ActionPerformed


    private void viewdereservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdereservasActionPerformed

    }//GEN-LAST:event_viewdereservasActionPerformed


    private void registrodevehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodevehiculosActionPerformed

    }//GEN-LAST:event_registrodevehiculosActionPerformed

    private void registrodeclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodeclientesActionPerformed

    }//GEN-LAST:event_registrodeclientesActionPerformed

    private void registrodereservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodereservacionesActionPerformed

    }//GEN-LAST:event_registrodereservacionesActionPerformed

    private void registrodeempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrodeempleadosActionPerformed

    }//GEN-LAST:event_registrodeempleadosActionPerformed

    private void AcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    //Getter y setters de todos los componentes
    //Para que los controladores puedan acceder
    // a sus acciones y tener que poner lo componentes 
    //publicos, y poder abrir los JInternalFrames/ MenuItems
    public JMenuItem getPanelRegistros() {
        return PanelRegistros;
    }

    public void setPanelRegistros(JMenuItem PanelRegistros) {
        this.PanelRegistros = PanelRegistros;
    }

    public JMenu getPaneldefacturacion() {
        return Paneldefacturacion;
    }

    public void setPaneldefacturacion(JMenu Paneldefacturacion) {
        this.Paneldefacturacion = Paneldefacturacion;
    }

    public JMenuItem getPaneldefacturacion1() {
        return paneldefacturacion1;
    }

    public void setPaneldefacturacion1(JMenuItem paneldefacturacion1) {
        this.paneldefacturacion1 = paneldefacturacion1;
    }

    public JMenuItem getRegistrodeclientes() {
        return registrodeclientes;
    }

    public void setRegistrodeclientes(JMenuItem registrodeclientes) {
        this.registrodeclientes = registrodeclientes;
    }

    public JMenuItem getRegistrodereservaciones() {
        return registrodereservaciones;
    }

    public void setRegistrodereservaciones(JMenuItem registrodereservaciones) {
        this.registrodereservaciones = registrodereservaciones;
    }

    public JMenuItem getRegistrodevehiculos() {
        return registrodevehiculos;
    }

    public void setRegistrodevehiculos(JMenuItem registrodevehiculos) {
        this.registrodevehiculos = registrodevehiculos;
    }

    public JMenuItem getViewdereservas() {
        return viewdereservas;
    }

    public void setViewdereservas(JMenuItem viewdereservas) {
        this.viewdereservas = viewdereservas;
    }

    public JMenuItem getRegistrodeempleados() {
        return registrodeempleados;
    }

    public void setRegistrodeempleados(JMenuItem registrodeempleados) {
        this.registrodeempleados = registrodeempleados;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JMenu getAcercaDe() {
        return AcercaDe;
    }

    public void setAcercaDe(JMenu AcercaDe) {
        this.AcercaDe = AcercaDe;
    }
    
      
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AcercaDe;
    private javax.swing.JMenuItem PanelRegistros;
    private javax.swing.JMenu Paneldefacturacion;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem paneldefacturacion1;
    private javax.swing.JMenuItem registrodeclientes;
    private javax.swing.JMenuItem registrodeempleados;
    private javax.swing.JMenuItem registrodereservaciones;
    private javax.swing.JMenuItem registrodevehiculos;
    private javax.swing.JMenuItem viewdereservas;
    // End of variables declaration//GEN-END:variables
}
