/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author 1000g
 */
public class PaneldeRegistros extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaneldeRegistros
     */
    public PaneldeRegistros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnregistrobuscar = new javax.swing.JButton();
        txtpanelregistrocedula = new javax.swing.JTextField();
        btnregistroactualizar = new javax.swing.JButton();
        btnregistroeliminar = new javax.swing.JButton();
        txtpanelregistroempleado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarro = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        txtpanelregistromatricula1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        btnregistrobuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnregistrobuscar.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        btnregistrobuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistrobuscar.setText("Buscar");
        btnregistrobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrobuscarActionPerformed(evt);
            }
        });

        txtpanelregistrocedula.setBackground(new java.awt.Color(255, 255, 255));
        txtpanelregistrocedula.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        txtpanelregistrocedula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula del Cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtpanelregistrocedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpanelregistrocedulaActionPerformed(evt);
            }
        });

        btnregistroactualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnregistroactualizar.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        btnregistroactualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistroactualizar.setText("Actualizar");
        btnregistroactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroactualizarActionPerformed(evt);
            }
        });

        btnregistroeliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnregistroeliminar.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        btnregistroeliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistroeliminar.setText("Eliminar");
        btnregistroeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroeliminarActionPerformed(evt);
            }
        });

        txtpanelregistroempleado.setBackground(new java.awt.Color(255, 255, 255));
        txtpanelregistroempleado.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        txtpanelregistroempleado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula del Empleado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtpanelregistroempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpanelregistroempleadoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(14, 20, 155));

        tblclientes.setBackground(new java.awt.Color(255, 255, 255));
        tblclientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        tblclientes.setFont(new java.awt.Font("Kalam", 1, 12)); // NOI18N
        tblclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Cedula", "Telefono", "Licencia", "Provincia", "Sector", "Calle", "N.º de la Casa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblclientes.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblclientes);

        tblCarro.setBackground(new java.awt.Color(255, 255, 255));
        tblCarro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tblCarro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tblCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IDCarro", "Marca", "Modelo", "Año", "N.º de Placa", "Matricula", "Kilometraje", "Precio Por dia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarroMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCarro);

        tblEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        tblEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tblEmpleados.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre del Empleado", "Apellido", "Cedula", "Salario", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblEmpleados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Kalam", 3, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Registros");
        jTextField1.setBorder(null);

        txtpanelregistromatricula1.setBackground(new java.awt.Color(255, 255, 255));
        txtpanelregistromatricula1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        txtpanelregistromatricula1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matricula del Vehiculo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtpanelregistromatricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpanelregistromatricula1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtpanelregistrocedula, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpanelregistromatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtpanelregistroempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnregistrobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnregistroactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnregistroeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpanelregistromatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpanelregistroempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnregistrobuscar)
                            .addComponent(btnregistroactualizar)
                            .addComponent(btnregistroeliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtpanelregistrocedula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclientesMouseClicked

    }//GEN-LAST:event_tblclientesMouseClicked

    private void btnregistrobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrobuscarActionPerformed

    }//GEN-LAST:event_btnregistrobuscarActionPerformed

    private void btnregistroactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroactualizarActionPerformed

    }//GEN-LAST:event_btnregistroactualizarActionPerformed

    private void btnregistroeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroeliminarActionPerformed

    }//GEN-LAST:event_btnregistroeliminarActionPerformed

    private void tblCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCarroMouseClicked

    private void txtpanelregistroempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpanelregistroempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpanelregistroempleadoActionPerformed

    private void txtpanelregistrocedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpanelregistrocedulaActionPerformed

    }//GEN-LAST:event_txtpanelregistrocedulaActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void txtpanelregistromatricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpanelregistromatricula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpanelregistromatricula1ActionPerformed

    //Getter y setters de todos los componentes
    //Para que los controladores puedan acceder
    // a sus acciones y tener que poner lo componentes 
    //publicos
    public JButton getBtnregistroeliminar() {
        return btnregistroeliminar;
    }

    public JButton getBtnregistroactualizar() {
        return btnregistroactualizar;
    }

    public JTable getTblEmpleados() {
        return tblEmpleados;
    }

    public JTextField getTxtpanelregistroempleado() {
        return txtpanelregistroempleado;
    }

    public JButton getBtnregistrobuscar() {
        return btnregistrobuscar;
    }

    public void setBtnregistrobuscar(JButton btnregistrobuscar) {
        this.btnregistrobuscar = btnregistrobuscar;
    }

    public JTable getTblCarro() {
        return tblCarro;
    }

    public void setTblCarro(JTable tblCarro) {
        this.tblCarro = tblCarro;
    }

    public JTable getTblclientes() {
        return tblclientes;
    }

    public void setTblclientes(JTable tblclientes) {
        this.tblclientes = tblclientes;
    }

    public JTextField getTxtpanelregistrocedula() {
        return txtpanelregistrocedula;
    }

    public void setTxtpanelregistrocedula(JTextField txtpanelregistrocedula) {
        this.txtpanelregistrocedula = txtpanelregistrocedula;
    }

    public JTextField getTxtpanelregistromatricula1() {
        return txtpanelregistromatricula1;
    }

    public void setTxtpanelregistromatricula1(JTextField txtpanelregistromatricula1) {
        this.txtpanelregistromatricula1 = txtpanelregistromatricula1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistroactualizar;
    private javax.swing.JButton btnregistrobuscar;
    private javax.swing.JButton btnregistroeliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblCarro;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTable tblclientes;
    private javax.swing.JTextField txtpanelregistrocedula;
    private javax.swing.JTextField txtpanelregistroempleado;
    private javax.swing.JTextField txtpanelregistromatricula1;
    // End of variables declaration//GEN-END:variables
}
