/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

/**
 *
 * @author 1000g
 */
public class PaneldeRegistrosparaEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaneldeRegistros
     */
    public PaneldeRegistrosparaEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnregistrobuscar = new javax.swing.JButton();
        txtpanelregistroparaempleadoscedula = new javax.swing.JTextField();
        btnregistroactualizar = new javax.swing.JButton();
        btnregistroeliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblmatricula = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        txtpanelregistroparaempleadosmatricula = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        btnregistrobuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnregistrobuscar.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        btnregistrobuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistrobuscar.setText("Buscar");
        btnregistrobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrobuscarActionPerformed(evt);
            }
        });

        txtpanelregistroparaempleadoscedula.setBackground(new java.awt.Color(255, 255, 255));
        txtpanelregistroparaempleadoscedula.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        txtpanelregistroparaempleadoscedula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula del Cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtpanelregistroparaempleadoscedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpanelregistroparaempleadoscedulaActionPerformed(evt);
            }
        });

        btnregistroactualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnregistroactualizar.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        btnregistroactualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistroactualizar.setText("Actualizar");
        btnregistroactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroactualizarActionPerformed(evt);
            }
        });

        btnregistroeliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnregistroeliminar.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        btnregistroeliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistroeliminar.setText("Eliminar");
        btnregistroeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroeliminarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(14, 20, 155));

        tblclientes.setBackground(new java.awt.Color(255, 255, 255));
        tblclientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        tblclientes.setFont(new java.awt.Font("Kalam", 1, 12)); // NOI18N
        tblclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Cedula", "Licencia", "Telefono", "Provincia", "Sector", "Calle", "N.º de la Casa"
            }
        ));
        tblclientes.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblclientes);

        tblmatricula.setBackground(new java.awt.Color(255, 255, 255));
        tblmatricula.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tblmatricula.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tblmatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Marca", "Modelo", "N.º de Placa", "Kilometraje", "Año"
            }
        ));
        tblmatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmatriculaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblmatricula);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Kalam", 3, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Registros");
        jTextField1.setBorder(null);

        txtpanelregistroparaempleadosmatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtpanelregistroparaempleadosmatricula.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        txtpanelregistroparaempleadosmatricula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matricula del Vehiculo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtpanelregistroparaempleadosmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpanelregistroparaempleadosmatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(txtpanelregistroparaempleadoscedula, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtpanelregistroparaempleadosmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnregistrobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnregistroactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnregistroeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 138, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpanelregistroparaempleadoscedula, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpanelregistroparaempleadosmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnregistrobuscar)
                            .addComponent(btnregistroactualizar)
                            .addComponent(btnregistroeliminar))
                        .addGap(28, 28, 28)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclientesMouseClicked

    }//GEN-LAST:event_tblclientesMouseClicked

    private void btnregistrobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrobuscarActionPerformed

    }//GEN-LAST:event_btnregistrobuscarActionPerformed

    private void btnregistroactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroactualizarActionPerformed

    }//GEN-LAST:event_btnregistroactualizarActionPerformed

    private void btnregistroeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroeliminarActionPerformed

    }//GEN-LAST:event_btnregistroeliminarActionPerformed

    private void tblmatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmatriculaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblmatriculaMouseClicked

    private void txtpanelregistroparaempleadoscedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpanelregistroparaempleadoscedulaActionPerformed

    }//GEN-LAST:event_txtpanelregistroparaempleadoscedulaActionPerformed

    private void txtpanelregistroparaempleadosmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpanelregistroparaempleadosmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpanelregistroparaempleadosmatriculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistroactualizar;
    private javax.swing.JButton btnregistrobuscar;
    private javax.swing.JButton btnregistroeliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblclientes;
    private javax.swing.JTable tblmatricula;
    private javax.swing.JTextField txtpanelregistroparaempleadoscedula;
    private javax.swing.JTextField txtpanelregistroparaempleadosmatricula;
    // End of variables declaration//GEN-END:variables
}
