package Views;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author 1000g
 */
public class RegistrodeCarros extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaneldeCarros
     */
    public RegistrodeCarros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtregistrocarrosaño = new javax.swing.JTextField();
        txtregistrocarrosmarca = new javax.swing.JTextField();
        txtregistrocarrosmatricula = new javax.swing.JTextField();
        txtregistrocarroskilometraje = new javax.swing.JTextField();
        txtregistrocarrosnumdeplaca = new javax.swing.JTextField();
        txtregistrocarrosmodelo = new javax.swing.JTextField();
        btnregistrocarrosagregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtregistrocarrospreciopordia = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtregistrocarrosaño.setBackground(new java.awt.Color(255, 255, 255));
        txtregistrocarrosaño.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Año", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtregistrocarrosaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrocarrosañoActionPerformed(evt);
            }
        });

        txtregistrocarrosmarca.setBackground(new java.awt.Color(255, 255, 255));
        txtregistrocarrosmarca.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marca", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtregistrocarrosmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrocarrosmarcaActionPerformed(evt);
            }
        });

        txtregistrocarrosmatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtregistrocarrosmatricula.setForeground(new java.awt.Color(51, 51, 255));
        txtregistrocarrosmatricula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matricula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtregistrocarrosmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrocarrosmatriculaActionPerformed(evt);
            }
        });

        txtregistrocarroskilometraje.setBackground(new java.awt.Color(255, 255, 255));
        txtregistrocarroskilometraje.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kilometraje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistrocarroskilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrocarroskilometrajeActionPerformed(evt);
            }
        });

        txtregistrocarrosnumdeplaca.setBackground(new java.awt.Color(255, 255, 255));
        txtregistrocarrosnumdeplaca.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "N.º  Placa", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistrocarrosnumdeplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrocarrosnumdeplacaActionPerformed(evt);
            }
        });

        txtregistrocarrosmodelo.setBackground(new java.awt.Color(255, 255, 255));
        txtregistrocarrosmodelo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistrocarrosmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrocarrosmodeloActionPerformed(evt);
            }
        });

        btnregistrocarrosagregar.setBackground(new java.awt.Color(0, 0, 0));
        btnregistrocarrosagregar.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        btnregistrocarrosagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistrocarrosagregar.setText("Aceptar");
        btnregistrocarrosagregar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnregistrocarrosagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrocarrosagregarActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Kalam", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese los datos del vehiculo");

        txtregistrocarrospreciopordia.setBackground(new java.awt.Color(255, 255, 255));
        txtregistrocarrospreciopordia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio por Dia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtregistrocarrospreciopordia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrocarrospreciopordiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtregistrocarrosmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistrocarrosmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistrocarrosmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistrocarrospreciopordia, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtregistrocarroskilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistrocarrosaño, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistrocarrosnumdeplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregistrocarrosagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtregistrocarrosmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistrocarrosnumdeplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtregistrocarrosmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistrocarroskilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtregistrocarrosaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistrocarrosmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtregistrocarrospreciopordia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregistrocarrosagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtregistrocarrosañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrocarrosañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrocarrosañoActionPerformed

    private void txtregistrocarrosmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrocarrosmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrocarrosmarcaActionPerformed

    private void txtregistrocarrosmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrocarrosmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrocarrosmatriculaActionPerformed

    private void txtregistrocarroskilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrocarroskilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrocarroskilometrajeActionPerformed

    private void txtregistrocarrosnumdeplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrocarrosnumdeplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrocarrosnumdeplacaActionPerformed

    private void txtregistrocarrosmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrocarrosmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrocarrosmodeloActionPerformed

    private void btnregistrocarrosagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrocarrosagregarActionPerformed

    }//GEN-LAST:event_btnregistrocarrosagregarActionPerformed

    private void txtregistrocarrospreciopordiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrocarrospreciopordiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrocarrospreciopordiaActionPerformed

    //Getter y setters de todos los componentes
    //Para que los controladores puedan acceder
    // a sus acciones y tener que poner lo componentes 
    //publicos
    public JButton getBtnregistrocarrosagregar() {
        return btnregistrocarrosagregar;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JTextField getTxtregistrocarrosaño() {
        return txtregistrocarrosaño;
    }

    public void setTxtregistrocarrosaño(JTextField txtregistrocarrosaño) {
        this.txtregistrocarrosaño = txtregistrocarrosaño;
    }

    public JTextField getTxtregistrocarroskilometraje() {
        return txtregistrocarroskilometraje;
    }

    public void setTxtregistrocarroskilometraje(JTextField txtregistrocarroskilometraje) {
        this.txtregistrocarroskilometraje = txtregistrocarroskilometraje;
    }

    public JTextField getTxtregistrocarrosmarca() {
        return txtregistrocarrosmarca;
    }

    public void setTxtregistrocarrosmarca(JTextField txtregistrocarrosmarca) {
        this.txtregistrocarrosmarca = txtregistrocarrosmarca;
    }

    public JTextField getTxtregistrocarrosmatricula() {
        return txtregistrocarrosmatricula;
    }

    public void setTxtregistrocarrosmatricula(JTextField txtregistrocarrosmatricula) {
        this.txtregistrocarrosmatricula = txtregistrocarrosmatricula;
    }

    public JTextField getTxtregistrocarrosmodelo() {
        return txtregistrocarrosmodelo;
    }

    public void setTxtregistrocarrosmodelo(JTextField txtregistrocarrosmodelo) {
        this.txtregistrocarrosmodelo = txtregistrocarrosmodelo;
    }

    public JTextField getTxtregistrocarrosnumdeplaca() {
        return txtregistrocarrosnumdeplaca;
    }

    public void setTxtregistrocarrosnumdeplaca(JTextField txtregistrocarrosnumdeplaca) {
        this.txtregistrocarrosnumdeplaca = txtregistrocarrosnumdeplaca;
    }

    public JTextField getTxtregistrocarrospreciopordia() {
        return txtregistrocarrospreciopordia;
    }

    public void setTxtregistrocarrospreciopordia(JTextField txtregistrocarrospreciopordia) {
        this.txtregistrocarrospreciopordia = txtregistrocarrospreciopordia;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrocarrosagregar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtregistrocarrosaño;
    private javax.swing.JTextField txtregistrocarroskilometraje;
    private javax.swing.JTextField txtregistrocarrosmarca;
    private javax.swing.JTextField txtregistrocarrosmatricula;
    private javax.swing.JTextField txtregistrocarrosmodelo;
    private javax.swing.JTextField txtregistrocarrosnumdeplaca;
    private javax.swing.JTextField txtregistrocarrospreciopordia;
    // End of variables declaration//GEN-END:variables
}
