/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author 1000g
 */
public class RegistrodeClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaneldeClientes
     */
    public RegistrodeClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtregistroclienteslicencia = new javax.swing.JTextField();
        txtregistroclientesapellido = new javax.swing.JTextField();
        txtregistroclientesnombre = new javax.swing.JTextField();
        txtregistroclientestelefono = new javax.swing.JTextField();
        btnregistroclientesagregar = new javax.swing.JButton();
        txtregistroclientescalle = new javax.swing.JTextField();
        txtregistroclientesnumdelacasa = new javax.swing.JTextField();
        txtregistroclientesprovincia = new javax.swing.JTextField();
        txtregistroclientescedula = new javax.swing.JTextField();
        txtregistroclientessector = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtregistroclienteslicencia.setBackground(new java.awt.Color(255, 255, 255));
        txtregistroclienteslicencia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Licencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistroclienteslicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistroclienteslicenciaActionPerformed(evt);
            }
        });

        txtregistroclientesapellido.setBackground(new java.awt.Color(255, 255, 255));
        txtregistroclientesapellido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtregistroclientesapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistroclientesapellidoActionPerformed(evt);
            }
        });

        txtregistroclientesnombre.setBackground(new java.awt.Color(255, 255, 255));
        txtregistroclientesnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistroclientesnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistroclientesnombreActionPerformed(evt);
            }
        });

        txtregistroclientestelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtregistroclientestelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistroclientestelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistroclientestelefonoActionPerformed(evt);
            }
        });

        btnregistroclientesagregar.setBackground(new java.awt.Color(0, 0, 0));
        btnregistroclientesagregar.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        btnregistroclientesagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnregistroclientesagregar.setText("Aceptar");
        btnregistroclientesagregar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnregistroclientesagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroclientesagregarActionPerformed(evt);
            }
        });

        txtregistroclientescalle.setBackground(new java.awt.Color(255, 255, 255));
        txtregistroclientescalle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistroclientescalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistroclientescalleActionPerformed(evt);
            }
        });

        txtregistroclientesnumdelacasa.setBackground(new java.awt.Color(255, 255, 255));
        txtregistroclientesnumdelacasa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "N.º de la Casa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistroclientesnumdelacasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistroclientesnumdelacasaActionPerformed(evt);
            }
        });

        txtregistroclientesprovincia.setBackground(new java.awt.Color(255, 255, 255));
        txtregistroclientesprovincia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Provincia", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistroclientesprovincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistroclientesprovinciaActionPerformed(evt);
            }
        });

        txtregistroclientescedula.setBackground(new java.awt.Color(255, 255, 255));
        txtregistroclientescedula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistroclientescedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistroclientescedulaActionPerformed(evt);
            }
        });

        txtregistroclientessector.setBackground(new java.awt.Color(255, 255, 255));
        txtregistroclientessector.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sector", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtregistroclientessector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistroclientessectorActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Kalam", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Registrese");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Kalam", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese sus datos");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Kalam", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingrese su Direccion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtregistroclienteslicencia)
                    .addComponent(txtregistroclientescedula)
                    .addComponent(txtregistroclientesapellido)
                    .addComponent(txtregistroclientesnombre)
                    .addComponent(txtregistroclientestelefono)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtregistroclientesprovincia, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(txtregistroclientessector)
                        .addComponent(txtregistroclientescalle)
                        .addComponent(txtregistroclientesnumdelacasa)
                        .addComponent(btnregistroclientesagregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtregistroclientesnombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistroclientesprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtregistroclientessector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistroclientesapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtregistroclientescalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistroclientescedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtregistroclientesnumdelacasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistroclienteslicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtregistroclientestelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregistroclientesagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtregistroclienteslicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistroclienteslicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistroclienteslicenciaActionPerformed

    private void txtregistroclientesapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistroclientesapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistroclientesapellidoActionPerformed

    private void txtregistroclientesnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistroclientesnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistroclientesnombreActionPerformed

    private void txtregistroclientestelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistroclientestelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistroclientestelefonoActionPerformed

    private void btnregistroclientesagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroclientesagregarActionPerformed

    }//GEN-LAST:event_btnregistroclientesagregarActionPerformed

    private void txtregistroclientescalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistroclientescalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistroclientescalleActionPerformed

    private void txtregistroclientesnumdelacasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistroclientesnumdelacasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistroclientesnumdelacasaActionPerformed

    private void txtregistroclientesprovinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistroclientesprovinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistroclientesprovinciaActionPerformed

    private void txtregistroclientescedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistroclientescedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistroclientescedulaActionPerformed

    private void txtregistroclientessectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistroclientessectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistroclientessectorActionPerformed

    //Getter y setters de todos los componentes
    //Para que los controladores puedan acceder
    // a sus acciones y tener que poner lo componentes 
    //publicos
    public JButton getBtnregistroclientesagregar() {
        return btnregistroclientesagregar;
    }

    public void setBtnregistroclientesagregar(JButton btnregistroclientesagregar) {
        this.btnregistroclientesagregar = btnregistroclientesagregar;
    }

    public JTextField getTxtregistroclientesapellido() {
        return txtregistroclientesapellido;
    }

    public void setTxtregistroclientesapellido(JTextField txtregistroclientesapellido) {
        this.txtregistroclientesapellido = txtregistroclientesapellido;
    }

    public JTextField getTxtregistroclientescalle() {
        return txtregistroclientescalle;
    }

    public void setTxtregistroclientescalle(JTextField txtregistroclientescalle) {
        this.txtregistroclientescalle = txtregistroclientescalle;
    }

    public JTextField getTxtregistroclientescedula() {
        return txtregistroclientescedula;
    }

    public void setTxtregistroclientescedula(JTextField txtregistroclientescedula) {
        this.txtregistroclientescedula = txtregistroclientescedula;
    }

    public JTextField getTxtregistroclienteslicencia() {
        return txtregistroclienteslicencia;
    }

    public void setTxtregistroclienteslicencia(JTextField txtregistroclienteslicencia) {
        this.txtregistroclienteslicencia = txtregistroclienteslicencia;
    }

    public JTextField getTxtregistroclientesnombre() {
        return txtregistroclientesnombre;
    }

    public void setTxtregistroclientesnombre(JTextField txtregistroclientesnombre) {
        this.txtregistroclientesnombre = txtregistroclientesnombre;
    }

    public JTextField getTxtregistroclientesnumdelacasa() {
        return txtregistroclientesnumdelacasa;
    }

    public void setTxtregistroclientesnumdelacasa(JTextField txtregistroclientesnumdelacasa) {
        this.txtregistroclientesnumdelacasa = txtregistroclientesnumdelacasa;
    }

    public JTextField getTxtregistroclientesprovincia() {
        return txtregistroclientesprovincia;
    }

    public void setTxtregistroclientesprovincia(JTextField txtregistroclientesprovincia) {
        this.txtregistroclientesprovincia = txtregistroclientesprovincia;
    }

    public JTextField getTxtregistroclientessector() {
        return txtregistroclientessector;
    }

    public void setTxtregistroclientessector(JTextField txtregistroclientessector) {
        this.txtregistroclientessector = txtregistroclientessector;
    }

    public JTextField getTxtregistroclientestelefono() {
        return txtregistroclientestelefono;
    }

    public void setTxtregistroclientestelefono(JTextField txtregistroclientestelefono) {
        this.txtregistroclientestelefono = txtregistroclientestelefono;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistroclientesagregar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtregistroclientesapellido;
    private javax.swing.JTextField txtregistroclientescalle;
    private javax.swing.JTextField txtregistroclientescedula;
    private javax.swing.JTextField txtregistroclienteslicencia;
    private javax.swing.JTextField txtregistroclientesnombre;
    private javax.swing.JTextField txtregistroclientesnumdelacasa;
    private javax.swing.JTextField txtregistroclientesprovincia;
    private javax.swing.JTextField txtregistroclientessector;
    private javax.swing.JTextField txtregistroclientestelefono;
    // End of variables declaration//GEN-END:variables
}
