/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author 1000g
 */
public class ViewReservacionesdeClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewReservacionesdeClientes
     */
    public ViewReservacionesdeClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtviewreservacionesdeclientescedula = new javax.swing.JTextField();
        btnviewreservacionesdeclientesbuscar = new javax.swing.JButton();
        btnviewreservacionesdeclientesborrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableviewreservaciones = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255)))); // NOI18N

        txtviewreservacionesdeclientescedula.setBackground(new java.awt.Color(255, 255, 255));
        txtviewreservacionesdeclientescedula.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        txtviewreservacionesdeclientescedula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese la Cedula", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalam", 3, 14), new java.awt.Color(0, 0, 0)))); // NOI18N
        txtviewreservacionesdeclientescedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtviewreservacionesdeclientescedulaActionPerformed(evt);
            }
        });

        btnviewreservacionesdeclientesbuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnviewreservacionesdeclientesbuscar.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        btnviewreservacionesdeclientesbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnviewreservacionesdeclientesbuscar.setText("Buscar");
        btnviewreservacionesdeclientesbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewreservacionesdeclientesbuscarActionPerformed(evt);
            }
        });

        btnviewreservacionesdeclientesborrar.setBackground(new java.awt.Color(0, 0, 0));
        btnviewreservacionesdeclientesborrar.setFont(new java.awt.Font("Kalam", 0, 14)); // NOI18N
        btnviewreservacionesdeclientesborrar.setForeground(new java.awt.Color(255, 255, 255));
        btnviewreservacionesdeclientesborrar.setText("Borrar");
        btnviewreservacionesdeclientesborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewreservacionesdeclientesborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnviewreservacionesdeclientesbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtviewreservacionesdeclientescedula, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnviewreservacionesdeclientesborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtviewreservacionesdeclientescedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnviewreservacionesdeclientesbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnviewreservacionesdeclientesborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(255, 255, 255)))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jtableviewreservaciones.setBackground(new java.awt.Color(255, 255, 255));
        jtableviewreservaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jtableviewreservaciones.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtableviewreservaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Telefono", "Marca del vehiculo", "Modelo", "Placa", "Precio por dia", "Fecha de Reserva", "Fecha de entrega", "Fecha devolucion", "Dias totales", "Monto estimado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableviewreservaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableviewreservacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableviewreservaciones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtviewreservacionesdeclientescedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtviewreservacionesdeclientescedulaActionPerformed

    }//GEN-LAST:event_txtviewreservacionesdeclientescedulaActionPerformed

    private void btnviewreservacionesdeclientesbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewreservacionesdeclientesbuscarActionPerformed

    }//GEN-LAST:event_btnviewreservacionesdeclientesbuscarActionPerformed

    private void jtableviewreservacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableviewreservacionesMouseClicked

    }//GEN-LAST:event_jtableviewreservacionesMouseClicked

    private void btnviewreservacionesdeclientesborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewreservacionesdeclientesborrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewreservacionesdeclientesborrarActionPerformed

    public JButton getBtnviewreservacionesdeclientesbuscar() {
        return btnviewreservacionesdeclientesbuscar;
    }

    public void setBtnviewreservacionesdeclientesbuscar(JButton btnviewreservacionesdeclientesbuscar) {
        this.btnviewreservacionesdeclientesbuscar = btnviewreservacionesdeclientesbuscar;
    }

    public JTable getJtableviewreservaciones() {
        return jtableviewreservaciones;
    }

    public void setJtableviewreservaciones(JTable jtableviewreservaciones) {
        this.jtableviewreservaciones = jtableviewreservaciones;
    }

    public JButton getBtnviewreservacionesdeclientesborrar() {
        return btnviewreservacionesdeclientesborrar;
    }

    public void setBtnviewreservacionesdeclientesborrar(JButton btnviewreservacionesdeclientesborrar) {
        this.btnviewreservacionesdeclientesborrar = btnviewreservacionesdeclientesborrar;
    }

    public JTextField getTxtviewreservacionesdeclientescedula() {
        return txtviewreservacionesdeclientescedula;
    }

    public void setTxtviewreservacionesdeclientescedula(JTextField txtviewreservacionesdeclientescedula) {
        this.txtviewreservacionesdeclientescedula = txtviewreservacionesdeclientescedula;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnviewreservacionesdeclientesborrar;
    private javax.swing.JButton btnviewreservacionesdeclientesbuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableviewreservaciones;
    private javax.swing.JTextField txtviewreservacionesdeclientescedula;
    // End of variables declaration//GEN-END:variables
}
